### ISSUE TITLE
Error JsonNumberImpl

### ISSUE THREAD

**Issue by Rub21** [osmlab/josm-tofix-plugin#102]
<img width="900" alt="screen shot 2017-07-27 at 12 12 27 pm" src="https://user-images.githubusercontent.com/1152236/28683152-2322b552-72c5-11e7-8dfe-9c9e19c0fd8d.png">

```
{{{
URL:http://josm.openstreetmap.de/svn/trunk
Repository:UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
Last:Changed Date: 2017-07-03 00:44:07 +0200 (Mon, 03 Jul 2017)
Build-Date:2017-07-02 23:26:36
Revision:12450
Relative:URL: ^/trunk

Identification: JOSM/1.5 (12450 en) Mac OS X 10.12.6
OS Build number: Mac OS X 10.12.6 (16G29)
Memory Usage: 856 MB / 3641 MB (596 MB allocated, but free)
Java version: 1.8.0_141-b15, Oracle Corporation, Java HotSpot(TM) 64-Bit Server VM
Screen: Display 69733568 1440x900, Display 458671429 1920x1080
Maximum Screen Size: 1920x1080

Plugins:
+ Mapillary (v1.5.5)
+ OpenStreetCam (93)
+ apache-commons (32994)
+ apache-http (32699)
+ buildings_tools (33004)
+ ejml (32680)
+ geojson (52)
+ geotools (33380)
+ jts (32699)
+ opendata (33358)
+ osm-obj-info (1484152384)
+ todo (30200)
+ tofix (1499206635)
+ utilsplugin2 (33328)

Map paint styles:
- https://josm.openstreetmap.de/josmfile?page=Styles/DestinationSignRelation&zip=1
+ ${HOME}/Applications/josm/destination.mapcss
- https://josm.openstreetmap.de/josmfile?page=Styles/Sidewalks&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/ShowID&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Modified&zip=1

Last errors/warnings:
- W: java.io.IOException: Attribution is not loaded yet
- W: java.io.IOException: Attribution is not loaded yet
- W: java.io.IOException: Attribution is not loaded yet
- W: java.io.IOException: Attribution is not loaded yet
- W: java.io.IOException: Attribution is not loaded yet
- W: java.io.IOException: Attribution is not loaded yet
- W: java.io.IOException: Attribution is not loaded yet
- W: java.io.IOException: Attribution is not loaded yet
- W: java.io.IOException: Attribution is not loaded yet
- E: Handled by bug report queue: java.lang.NullPointerException


=== REPORTED CRASH DATA ===
BugReportExceptionHandler#handleException:
No data collected.

Warning issued by: BugReportExceptionHandler#handleException

=== STACK TRACE ===
Thread: AWT-EventQueue-0 (17) of main
java.lang.NullPointerException
	at org.openstreetmap.josm.plugins.tofix.TofixTask.work_osmlintlinestring(TofixTask.java:85)
	at org.openstreetmap.josm.plugins.tofix.TofixTask.work(TofixTask.java:48)
	at org.openstreetmap.josm.plugins.tofix.TofixDialog.get_new_item(TofixDialog.java:462)
	at org.openstreetmap.josm.plugins.tofix.TofixDialog.actionPerformed(TofixDialog.java:422)
	at javax.swing.JComboBox.fireActionEvent(JComboBox.java:1258)
	at javax.swing.JComboBox.setSelectedItem(JComboBox.java:586)
	at javax.swing.JComboBox.setSelectedIndex(JComboBox.java:622)
	at javax.swing.plaf.basic.BasicComboPopup$Handler.mouseReleased(BasicComboPopup.java:861)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at com.apple.laf.AquaComboBoxPopup$1.processMouseEvent(AquaComboBoxPopup.java:157)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
}}}
```
cc. @samely

**Comment by ashleyannmathew** [comment]
![pasted image at 2017_08_01 09_51 am](https://user-images.githubusercontent.com/28762545/28857443-29454534-7767-11e7-9965-cf324ff9210c.png)
Currently we are not able to connect to-fix tasks - “Missing Entrance Destination, Invalid motorways ” via JOSM directly. We are connecting through the web interface. It will be much faster if we could directly connect via JOSM. The error we get is as shown in the screenshot.
cc: @samely

**Comment by samely** [comment]
I've already fixed this:
![image](https://user-images.githubusercontent.com/10425629/28941505-dfe325b2-785d-11e7-9cea-fcdf2d2110d1.png)
Thanks for pointing it :bowing_woman:
