### ISSUE TITLE
Crashing on JOSM r9842

### ISSUE THREAD

**Issue by maning** [osmlab/josm-tofix-plugin#32]
```
{{{
URL:http://josm.openstreetmap.de/svn/trunk
Repository:UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
Last:Changed Date: 2016-02-20 02:10:49 +0100 (Sat, 20 Feb 2016)
Build-Date:2016-02-20 02:31:54
Revision:9842
Relative:URL: ^/trunk

Identification: JOSM/1.5 (9842 en) Mac OS X 10.10.5
Memory Usage: 794 MB / 1820 MB (167 MB allocated, but free)
Java version: 1.8.0_60-b27, Oracle Corporation, Java HotSpot(TM) 64-Bit Server VM
VM arguments: [-Djosm.pref=/Users/maning/osm/josm_preferences/]
Dataset consistency test: No problems found

Plugins:
- DirectDownload (31934)
- DirectUpload (31912)
- FastDraw (31895)
- ImageWayPoint (31772)
- ImportImagePlugin (31772)
- Mapillary (32040)
- PicLayer (31895)
- RoadSigns (31895)
- apache-commons (31895)
- apache-http (31895)
- buildings_tools (31895)
- changesetID (UNKNOWN)
- continuosDownload (1446070193)
- editgpx (31772)
- ejml (31895)
- ext_tools (31772)
- fieldpapers (v0.4.0)
- geochat (31895)
- geotools (31895)
- imagery_offset_db (32046)
- imageryadjust (31772)
- jts (31772)
- log4j (31895)
- mbtiles (v2.0)
- measurement (31895)
- opendata (32071)
- pbf (31772)
- photo_geotagging (31895)
- rasterfilters (31895)
- reltoolbox (31895)
- reverter (32005)
- routing (31772)
- scripting (30722)
- tag2link (31910)
- terracer (31895)
- todo (29154)
- tofix (173)
- turnlanes (31772)
- turnrestrictions (31895)
- utilsplugin2 (32018)

Last errors/warnings:
- W: Failed to rename file /Users/maning/Library/Caches/JOSM/mirror_https___josm.openstreetmap.de_josmfile_page_Styles_Lane_features_zip_1.tmp to /Users/maning/Library/Caches/JOSM/mirror_https___josm.openstreetmap.de_josmfile_page_Styles_Lane_features_zip_1.
- W: Failed to rename file /Users/maning/Library/Caches/JOSM/mirror_https___josm.openstreetmap.de_josmfile_page_Styles_Lane_features_ryg_zip_1.tmp to /Users/maning/Library/Caches/JOSM/mirror_https___josm.openstreetmap.de_josmfile_page_Styles_Lane_features_ryg_zip_1.
- E: Failed to locate image 'styles/standard/vehicle/restriction/right_of_way.png'
- W: Mappaint style "standard" (Direction for traffic signs) icon "styles/standard/vehicle/restriction/right_of_way.png" not found.
- E: java.lang.NullPointerException: Value in JsonObjects name/value pair cannot be null

java.lang.NullPointerException: Value in JsonObjects name/value pair cannot be null
    at org.glassfish.json.JsonObjectBuilderImpl.validateValue(JsonObjectBuilderImpl.java:164)
    at org.glassfish.json.JsonObjectBuilderImpl.add(JsonObjectBuilderImpl.java:74)
    at org.openstreetmap.josm.plugins.tofix.controller.ItemTrackController.send_track_edit(ItemTrackController.java:18)
    at org.openstreetmap.josm.plugins.tofix.TofixDialog.edit(TofixDialog.java:289)
    at org.openstreetmap.josm.plugins.tofix.TofixDialog.get_new_item(TofixDialog.java:335)
    at org.openstreetmap.josm.plugins.tofix.TofixDialog.actionPerformed(TofixDialog.java:271)
    at javax.swing.JComboBox.fireActionEvent(JComboBox.java:1258)
    at javax.swing.JComboBox.setSelectedItem(JComboBox.java:586)
    at javax.swing.JComboBox.setSelectedIndex(JComboBox.java:622)
    at javax.swing.plaf.basic.BasicComboPopup$Handler.mouseReleased(BasicComboPopup.java:852)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
    at java.awt.Component.processMouseEvent(Component.java:6535)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at javax.swing.plaf.basic.BasicComboPopup$1.processMouseEvent(BasicComboPopup.java:501)
    at java.awt.Component.processEvent(Component.java:6300)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4891)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
}}}
```

**Comment by Rub21** [comment]
I've checked out this error, I could not reproduce the error.

to reproduce the error I've used  https://josm.openstreetmap.de/download/josm-snapshot-9842.jar. even I've used latest versions

So i think the error is on `JsonObjects` to-fix usees it to get the data from server.

**Comment by Rub21** [comment]
no more actions here , Close here!
