### ISSUE TITLE
to-fix does not find object to select after installed

### ISSUE THREAD

**Issue by Rub21** [osmlab/josm-tofix-plugin#45]
```
WARNING: JOSM expected to find primitive [node 13050675] in dataset but it is not there. Please report this at https://josm.openstreetmap.de. This is not a critical error, it should be safe to continue in your work.
ERROR: java.lang.Exception
java.lang.Exception
    at org.openstreetmap.josm.data.osm.DataSet.getPrimitiveByIdChecked(DataSet.java:966)
    at org.openstreetmap.josm.data.osm.DataSet.addSelected(DataSet.java:804)
    at org.openstreetmap.josm.data.osm.DataSet.setSelected(DataSet.java:734)
    at org.openstreetmap.josm.data.osm.DataSet.setSelected(DataSet.java:754)
    at org.openstreetmap.josm.plugins.tofix.util.Download$1.run(Download.java:47)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
WARNING: JOSM expected to find primitive [relation 13050675] in dataset but it is not there. Please report this at https://josm.openstreetmap.de. This is not a critical error, it should be safe to continue in your work.
ERROR: java.lang.Exception
java.lang.Exception
    at org.openstreetmap.josm.data.osm.DataSet.getPrimitiveByIdChecked(DataSet.java:966)
    at org.openstreetmap.josm.data.osm.DataSet.addSelected(DataSet.java:804)
    at org.openstreetmap.josm.data.osm.DataSet.setSelected(DataSet.java:734)
    at org.openstreetmap.josm.data.osm.DataSet.setSelected(DataSet.java:754)
    at org.openstreetmap.josm.plugins.tofix.util.Download$1.run(Download.java:47)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

![image](https://cloud.githubusercontent.com/assets/1152236/15341512/c315ec8c-1c54-11e6-9401-adf796025e27.png)

cc. @samely

**Comment by samely** [comment]
Since this doesn't happen again, closing here.
