### ISSUE TITLE
ToFix  - Excepcion Inesperada

### ISSUE THREAD

**Issue by ridixcr** [osmlab/josm-tofix-plugin#61]
Excepcion inesperada a la hora de iniciar el JOSM y poner imagen de Bing
![seleccion_034](https://cloud.githubusercontent.com/assets/1646072/16698321/5dd8d842-4513-11e6-94f3-0cd3896b39e3.png)

`ERROR: org.openstreetmap.josm.plugins.PluginException: An error occurred in plugin tofix. Cause: java.lang.reflect.InvocationTargetException. Cause: java.lang.NoSuchMethodError: org.openstreetmap.josm.tools.ImageResource.attachImageIcon(Ljavax/swing/AbstractAction;)V
org.openstreetmap.josm.plugins.PluginException: An error occurred in plugin tofix
    at org.openstreetmap.josm.plugins.PluginProxy.handlePluginException(PluginProxy.java:39)
    at org.openstreetmap.josm.plugins.PluginProxy.mapFrameInitialized(PluginProxy.java:49)
    at org.openstreetmap.josm.Main.setMapFrame(Main.java:529)
    at org.openstreetmap.josm.Main.createMapFrame(Main.java:804)
    at org.openstreetmap.josm.Main.addLayer(Main.java:791)
    at org.openstreetmap.josm.Main.addLayer(Main.java:776)
    at org.openstreetmap.josm.Main.addLayer(Main.java:763)
    at org.openstreetmap.josm.actions.AddImageryLayerAction.actionPerformed(AddImageryLayerAction.java:81)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
    at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
    at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
    at java.awt.Component.processMouseEvent(Component.java:6535)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6300)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4891)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.openstreetmap.josm.plugins.PluginProxy.mapFrameInitialized(PluginProxy.java:45)
    ... 45 more
Caused by: java.lang.NoSuchMethodError: org.openstreetmap.josm.tools.ImageResource.attachImageIcon(Ljavax/swing/AbstractAction;)V
    at org.openstreetmap.josm.plugins.tofix.TofixDialog$3.<init>(TofixDialog.java:158)
    at org.openstreetmap.josm.plugins.tofix.TofixDialog.<init>(TofixDialog.java:155)
    at org.openstreetmap.josm.plugins.tofix.TofixPlugin.mapFrameInitialized(TofixPlugin.java:22)
    ... 50 more
INFO: AbstractTileSourceLayer: estimated visible tiles: 54, estimated cache size: 108`

**Comment by samely** [comment]
This is not happening anymore.
