### ISSUE TITLE
Error  to display MultiPoint data

### ISSUE THREAD

**Issue by Rub21** [osmlab/josm-tofix-plugin#68]
```
{{{
URL:http://josm.openstreetmap.de/svn/trunk
Repository:UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
Last:Changed Date: 2016-09-06 00:16:07 +0200 (Tue, 06 Sep 2016)
Build-Date:2016-09-05 22:21:00
Revision:10966
Relative:URL: ^/trunk

Identification: JOSM/1.5 (10966 en) Linux Ubuntu 14.04.5 LTS
Memory Usage: 552 MB / 1756 MB (310 MB allocated, but free)
Java version: 1.8.0-ea-b108, Oracle Corporation, Java HotSpot(TM) 64-Bit Server VM
Screen: :0.0 1920x1080
Maximum Screen Size: 1920x1080

Plugins:
+ ColorPlugin (1414145445)
+ Create_grid_of_ways (32699)
+ FastDraw (32938)
+ ImportImagePlugin (32699)
+ PicLayer (32796)
+ apache-commons (32699)
+ auto_tools (1471534390)
+ buildings_tools (32944)
+ ejml (32680)
+ geojson (43)
+ geotools (32813)
+ imagery_offset_db (32796)
+ jogl (1.0.46)
+ jts (32699)
+ log4j (32699)
+ opendata (32898)
+ osm-obj-info (1468276210)
+ reverter (32796)
+ todo (30000)
+ tofix (1470237162)
+ turnlanes-tagging (245)
+ utilsplugin2 (32815)

Tagging presets:
+ https://josm.openstreetmap.de/josmfile?page=Presets/Maxspeed-zones&zip=1

Map paint styles:
+ https://gist.githubusercontent.com/Rub21/9f0aedb1f9b604843fc677d63939f0e5/raw/50881225329a8d04354b5345b90183e74b75a4b7/modifiedNodes.mapcss
- https://josm.openstreetmap.de/josmfile?page=Styles/NoFeature&zip=1

Last errors/warnings:
- W: java.io.IOException: Attribution is not loaded yet
- W: java.io.IOException: Attribution is not loaded yet
- W: java.io.IOException: Attribution is not loaded yet
- W: java.io.IOException: Attribution is not loaded yet
- W: java.io.IOException: Attribution is not loaded yet
- W: java.io.IOException: Attribution is not loaded yet
- W: java.io.IOException: Attribution is not loaded yet
- W: java.io.IOException: Attribution is not loaded yet
- W: java.io.IOException: Attribution is not loaded yet
- W: java.io.IOException: Attribution is not loaded yet


=== REPORTED CRASH DATA ===
BugReportExceptionHandler#handleException:
No data collected.

Warning issued by: BugReportExceptionHandler#handleException

=== STACK TRACE ===
Thread: AWT-EventQueue-0 (18) of main
java.lang.ArrayIndexOutOfBoundsException: 1
    at org.openstreetmap.josm.plugins.tofix.bean.items.ItemOsmlintMultipoint.get_nodes(ItemOsmlintMultipoint.java:42)
    at org.openstreetmap.josm.plugins.tofix.TofixTask.work_osmlintmultipoint(TofixTask.java:182)
    at org.openstreetmap.josm.plugins.tofix.TofixTask.work(TofixTask.java:73)
    at org.openstreetmap.josm.plugins.tofix.TofixDialog.get_new_item(TofixDialog.java:418)
    at org.openstreetmap.josm.plugins.tofix.TofixDialog.actionPerformed(TofixDialog.java:356)
    at javax.swing.JComboBox.fireActionEvent(JComboBox.java:1260)
    at javax.swing.JComboBox.setSelectedItem(JComboBox.java:588)
    at javax.swing.JComboBox.setSelectedIndex(JComboBox.java:624)
    at javax.swing.plaf.basic.BasicComboPopup$Handler.mouseReleased(BasicComboPopup.java:834)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
    at java.awt.Component.processMouseEvent(Component.java:6522)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3322)
    at javax.swing.plaf.basic.BasicComboPopup$1.processMouseEvent(BasicComboPopup.java:498)
    at java.awt.Component.processEvent(Component.java:6287)
    at java.awt.Container.processEvent(Container.java:2229)
    at java.awt.Component.dispatchEventImpl(Component.java:4878)
    at java.awt.Container.dispatchEventImpl(Container.java:2287)
    at java.awt.Component.dispatchEvent(Component.java:4700)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4872)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4528)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4457)
    at java.awt.Container.dispatchEventImpl(Container.java:2273)
    at java.awt.Window.dispatchEventImpl(Window.java:2706)
    at java.awt.Component.dispatchEvent(Component.java:4700)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:743)
    at java.awt.EventQueue.access$400(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:691)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:716)
    at java.awt.EventQueue$4.run(EventQueue.java:714)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:713)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:220)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:135)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:123)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:119)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:111)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:97)
}}}
```

http://osmlab.github.io/to-fix/#/task/crossinghighwaysandbuildings

cc. @samely

**Comment by Rub21** [comment]
This is going to fix here https://github.com/JOSM/tofix/pull/71
