### ISSUE TITLE
Crash at JOSM v11179

### ISSUE THREAD

**Issue by maning** [osmlab/josm-tofix-plugin#70]
```
{{{
URL:http://josm.openstreetmap.de/svn/trunk
Repository:UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
Last:Changed Date: 2016-10-27 00:37:50 +0200 (Thu, 27 Oct 2016)
Build-Date:2016-10-27 01:34:54
Revision:11179
Relative:URL: ^/trunk

Identification: JOSM/1.5 (11179 en) Mac OS X 10.12.1
Memory Usage: 815 MB / 1820 MB (475 MB allocated, but free)
Java version: 1.8.0_60-b27, Oracle Corporation, Java HotSpot(TM) 64-Bit Server VM
Screen: Display 69680256 1366x768
Maximum Screen Size: 1366x768
VM arguments: [-Djosm.pref=<josm.pref>/]

Plugins:
+ BuildingGeneralization (1010)
+ CommandLine (32796)
+ DirectDownload (32699)
+ DirectUpload (32699)
+ FastDraw (32938)
+ Mapillary (v1.3.1)
+ apache-commons (32699)
+ apache-http (32699)
+ auto_tools (1471534390)
+ buildings_tools (32944)
+ continuosDownload (53)
+ dataimport (32699)
+ ejml (32680)
+ ext_tools (32796)
+ geotools (32813)
+ gpxfilter (32699)
+ imagery_offset_db (32796)
+ jts (32699)
+ measurement (32936)
+ michigan_left (32699)
+ opendata (32898)
+ osm-obj-info (1468276210)
+ photo_geotagging (32699)
+ reverter (32796)
+ tageditor (33021)
+ terracer (33031)
+ todo (30000)
+ tofix (1470237162)
+ turnlanes-tagging (252)
+ utilsplugin2 (32815)
+ wikipedia (33017)

Tagging presets:
+ https://josm.openstreetmap.de/josmfile?page=Presets/LaneAttributes&zip=1

Map paint styles:
- https://github.com/hotosm/HDM-JOSM-style/archive/master.zip
+ https://github.com/gmgeo/osmic-josm-style/archive/master.zip
+ https://josm.openstreetmap.de/josmfile?page=Styles/LessObtrusiveNodes&zip=1
- https://raw.githubusercontent.com/Andygol/josm-styles/master/created_in_2015.mapcss
+ ${HOME}/osm/version.mapcss
- https://josm.openstreetmap.de/josmfile?page=Styles/Sidewalks&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Maxspeed&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Lane_and_Road_Attributes&zip=1
- https://raw.githubusercontent.com/species/josm-preset-traffic_sign_direction/master/direction.mapcss
- https://josm.openstreetmap.de/josmfile?page=Styles/Lane_features&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Lane_features_ryg&zip=1
+ https://josm.openstreetmap.de/josmfile?page=Styles/Coloured_buildings&zip=1
- https://raw.githubusercontent.com/osmlab/sf_building_height_import/master/buildingheights.css
- https://josm.openstreetmap.de/josmfile?page=Styles/LayerChecker&zip=1

Validator rules:
+ https://gist.githubusercontent.com/<user.name>/80414b47cdf160710287bf99e208b552/raw/4d429639e43de18da58d669f595844eb43faf86a/labuilding.mapcss

Last errors/warnings:
- W: java.io.IOException: Attribution is not loaded yet
- W: java.io.IOException: Attribution is not loaded yet
- W: java.io.IOException: Attribution is not loaded yet
- W: java.io.IOException: Attribution is not loaded yet
- W: java.io.IOException: Attribution is not loaded yet
- W: java.io.IOException: Attribution is not loaded yet
- W: java.io.IOException: Attribution is not loaded yet
- W: java.io.IOException: Attribution is not loaded yet
- W: java.io.IOException: Attribution is not loaded yet
- W: java.io.IOException: Attribution is not loaded yet


=== REPORTED CRASH DATA ===
BugReportExceptionHandler#handleException:
No data collected.

Warning issued by: BugReportExceptionHandler#handleException

=== STACK TRACE ===
Thread: AWT-EventQueue-0 (17) of main
java.lang.NullPointerException: Value in JsonObjects name/value pair cannot be null
    at org.glassfish.json.JsonObjectBuilderImpl.validateValue(JsonObjectBuilderImpl.java:164)
    at org.glassfish.json.JsonObjectBuilderImpl.add(JsonObjectBuilderImpl.java:74)
    at org.openstreetmap.josm.plugins.tofix.controller.ItemTrackController.send_track_edit(ItemTrackController.java:18)
    at org.openstreetmap.josm.plugins.tofix.TofixDialog.edit(TofixDialog.java:374)
    at org.openstreetmap.josm.plugins.tofix.TofixDialog.get_new_item(TofixDialog.java:419)
    at org.openstreetmap.josm.plugins.tofix.TofixDialog.actionPerformed(TofixDialog.java:356)
    at javax.swing.JComboBox.fireActionEvent(JComboBox.java:1258)
    at javax.swing.JComboBox.setSelectedItem(JComboBox.java:586)
    at javax.swing.JComboBox.setSelectedIndex(JComboBox.java:622)
    at javax.swing.plaf.basic.BasicComboPopup$Handler.mouseReleased(BasicComboPopup.java:852)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
    at java.awt.Component.processMouseEvent(Component.java:6535)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at javax.swing.plaf.basic.BasicComboPopup$1.processMouseEvent(BasicComboPopup.java:501)
    at java.awt.Component.processEvent(Component.java:6300)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4891)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
}}}

```

@Rub21

**Comment by Rub21** [comment]
This issue was fixed, @maning  can you add here how did you resolve this?

**Comment by maning** [comment]
Tested today with v11233 @Rub21 

```
{{{
URL:http://josm.openstreetmap.de/svn/trunk
Repository:UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
Last:Changed Date: 2016-11-10 22:57:06 +0100 (Thu, 10 Nov 2016)
Build-Date:2016-11-11 02:36:16
Revision:11233
Relative:URL: ^/trunk

Identification: JOSM/1.5 (11233 en) Mac OS X 10.12.1
Memory Usage: 864 MB / 1820 MB (287 MB allocated, but free)
Java version: 1.8.0_60-b27, Oracle Corporation, Java HotSpot(TM) 64-Bit Server VM
Screen: Display 69680256 1366x768
Maximum Screen Size: 1366x768
VM arguments: [-Djosm.pref=<josm.pref>/]

Plugins:
+ BuildingGeneralization (1010)
+ CommandLine (32796)
+ DirectDownload (32699)
+ DirectUpload (32699)
+ FastDraw (32938)
+ Mapillary (v1.3.2)
+ apache-commons (32699)
+ apache-http (32699)
+ auto_tools (1471534390)
+ buildings_tools (32944)
+ continuosDownload (53)
+ dataimport (32699)
+ ejml (32680)
+ ext_tools (32796)
+ geotools (33042)
+ gpxfilter (32699)
+ imagery_offset_db (32796)
+ jts (32699)
+ measurement (32936)
+ michigan_left (32699)
+ opendata (33051)
+ osm-obj-info (1468276210)
+ pbf (32865)
+ photo_geotagging (32699)
+ reverter (32796)
+ tageditor (33021)
+ terracer (33031)
+ todo (30000)
+ tofix (1479394193)
+ turnlanes-tagging (252)
+ utilsplugin2 (32815)
+ wikipedia (33070)

Tagging presets:
+ https://josm.openstreetmap.de/josmfile?page=Presets/LaneAttributes&zip=1
+ https://josm.openstreetmap.de/josmfile?page=Presets/Quick-highways&zip=1

Map paint styles:
- https://github.com/hotosm/HDM-JOSM-style/archive/master.zip
+ https://github.com/gmgeo/osmic-josm-style/archive/master.zip
+ https://josm.openstreetmap.de/josmfile?page=Styles/LessObtrusiveNodes&zip=1
- https://raw.githubusercontent.com/Andygol/josm-styles/master/created_in_2015.mapcss
+ ${HOME}/osm/version.mapcss
- https://josm.openstreetmap.de/josmfile?page=Styles/Sidewalks&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Maxspeed&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Lane_and_Road_Attributes&zip=1
- https://raw.githubusercontent.com/species/josm-preset-traffic_sign_direction/master/direction.mapcss
- https://josm.openstreetmap.de/josmfile?page=Styles/Lane_features&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Lane_features_ryg&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Coloured_buildings&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/LayerChecker&zip=1
- ${HOME}/projects/git/sf_building_height_import/buildingheights.css

Validator rules:
+ https://gist.githubusercontent.com/<user.name>/80414b47cdf160710287bf99e208b552/raw/4d429639e43de18da58d669f595844eb43faf86a/labuilding.mapcss

Last errors/warnings:
- W: Unable to get color from '' for color preference 'extrude.main.line'
- W: Unable to get color from '' for color preference 'improve.way.accuracy.helper.line'
- W: Unable to get color from '' for color preference 'make.parallel.helper.line'
- W: java.util.zip.ZipException: error in opening zip file
- W: PluginException: : org.openstreetmap.josm.plugins.PluginException: Invalid jar file '<josm.userdata>/plugins/josm-geojson.jar.new'
- W: Failed to scan file 'josm-geojson.jar.new' for plugin information. Skipping.
- W: Old style SideButton usage for action org.openstreetmap.josm.plugins.tofix.TofixDialog$3@5e7828a
- W: Old style SideButton usage for action org.openstreetmap.josm.plugins.tofix.TofixDialog$4@12e4819c
- W: Old style SideButton usage for action org.openstreetmap.josm.plugins.tofix.TofixDialog$5@3c8d694d
- E: Handled by bug report queue: java.lang.NullPointerException: Value in JsonObjects name/value pair cannot be null


=== REPORTED CRASH DATA ===
BugReportExceptionHandler#handleException:
No data collected.

Warning issued by: BugReportExceptionHandler#handleException

=== STACK TRACE ===
Thread: AWT-EventQueue-0 (17) of main
java.lang.NullPointerException: Value in JsonObjects name/value pair cannot be null
    at org.glassfish.json.JsonObjectBuilderImpl.validateValue(JsonObjectBuilderImpl.java:164)
    at org.glassfish.json.JsonObjectBuilderImpl.add(JsonObjectBuilderImpl.java:74)
    at org.openstreetmap.josm.plugins.tofix.controller.ItemTrackController.send_track_edit(ItemTrackController.java:18)
    at org.openstreetmap.josm.plugins.tofix.TofixDialog.edit(TofixDialog.java:378)
    at org.openstreetmap.josm.plugins.tofix.TofixDialog.get_new_item(TofixDialog.java:402)
    at org.openstreetmap.josm.plugins.tofix.TofixDialog.actionPerformed(TofixDialog.java:362)
    at javax.swing.JComboBox.fireActionEvent(JComboBox.java:1258)
    at javax.swing.JComboBox.setSelectedItem(JComboBox.java:586)
    at javax.swing.JComboBox.setSelectedIndex(JComboBox.java:622)
    at javax.swing.plaf.basic.BasicComboPopup$Handler.mouseReleased(BasicComboPopup.java:852)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
    at java.awt.Component.processMouseEvent(Component.java:6535)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at javax.swing.plaf.basic.BasicComboPopup$1.processMouseEvent(BasicComboPopup.java:501)
    at java.awt.Component.processEvent(Component.java:6300)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4891)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
}}}
```

**Comment by samely** [comment]
@maning can you test again? I think I've already fixed this.

**Comment by samely** [comment]
Can you test again @maning? I think I've already fixed it.

**Comment by samely** [comment]
@maning the plugin [has been updated](https://github.com/JOSM/tofix/pull/75). Just update the JOSM and plugin.
